services:
  database:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # MYSQL_DATABASE: Empty here to allow multiple database with this one connection if using JUnit
      MYSQL_ROOT_PASSWORD: root
